### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by Fuzzipede** [triture/priori#2]
Hi,
Priori looks great. Wanted to test it with the hello world tutorial. When I build it, i get an compilation Error
` 3. Generating javascript file from Haxe code...
     -----------------------------------------------

     - Running haxe command... 
- haxe args: -lib jQueryExtern -lib priori -cp src -cp build\__temp_compiler -main Priori_auto_main_builder -js build\js\priori.js

C:\HaxeToolkit\haxe\lib/jQueryExtern/3,0,0/js/jquery/Utils.hx:13: characters 15-22 : /
C:\HaxeToolkit\haxe\lib/jQueryExtern/3,0,0/js/jquery/Config.hx:50: characters 9-56 : Called from
C:\HaxeToolkit\haxe\lib/jQueryExtern/3,0,0/js/jquery/Config.hx:100: characters 37-44 : Called from
C:\HaxeToolkit\haxe\lib/jQueryExtern/3,0,0/js/jquery/Event.hx:3: characters 2-7 : Called from
Aborted

     Error...
     -------------------------
     |                                   |
     |   Compilation Error   |
     |                                  |
     -------------------------`

Haxe 3.2.1
jQueryExtern 3.0.0
Priori 0.8.1 or 0.7.1

**Comment by Fuzzipede** [comment]
Tried with Haxe 3.4.2 works! Sorry!

**Comment by felipevex** [comment]
Hi @Fuzzipede 
Thanks for your feedback. Let me know if you need any help.
